# Generated by Django 3.2.1 on 2021-08-14 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_hist'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='ids',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
