# Generated by Django 3.2.1 on 2021-08-14 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_auto_20210814_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hist',
            name='ids',
        ),
    ]
